<?php

use App\Movie;
use App\Tag;
use Illuminate\Database\Seeder;

class MovieTagSeeder extends Seeder
{
    protected $tag = '';
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $all_data = [
               [  'tag' => ['Happy', 'English', 'Alone'],       'movies'  =>  [ ['title'    =>  'Godzilla vs. Kong'                   ], ['title' => 'The Suicide Squad'                                ], ['title' => 'Aquaman'],                                                                                                                       ], ],
               [  'tag' => ['Happy', 'English', 'Date'],        'movies'  =>  [ ['title'    =>  'Wonder Woman'                        ], ['title' => 'The Gentlemen'                                    ], ['title' => 'Black Widow'],                                                                                                                   ], ],
               [  'tag' => ['Happy', 'English', 'Family'],      'movies'  =>  [ ['title'    =>  'Mulan'                               ], ['title' => 'Moana'                                            ], ['title' => 'Harry Potter and the Chamber of Secrets'],                                                                                       ], ],
               [  'tag' => ['Happy', 'English', 'Kids'],        'movies'  =>  [ ['title'    =>  'WALL·E'                              ], ['title' => 'Tom and Jerry'                                    ], ['title' => 'Spider-Man: Into the Spider-Verse'],       ['title' => 'Red Shoes and the Seven Dwarfs'],                                        ], ],
               [  'tag' => ['Happy', 'English', 'Friends'],     'movies'  =>  [ ['title'    =>  'Alpha'                               ], ['title' => 'Rampage'                                          ], ['title' => 'Skyscraper'],                                                                                                                    ], ],
               [  'tag' => ['Happy', 'Arabic', 'Alone'],        'movies'  =>  [ ['title'    =>  'Mosul'                               ], ['title' => 'The Blue Elephant'                                ], ['title' => 'The Blue Elephant 2'],                                                                                                           ], ],
               [  'tag' => ['Happy', 'Arabic', 'Date'],         'movies'  =>  [ ['title'    =>  'Sons of Rizk 2'                      ], ['title' => 'Sons of Rizk'                                     ], ['title' => 'The Secret Men Club'],                                                                                                           ], ],
               [  'tag' => ['Happy', 'Arabic', 'Family'],       'movies'  =>  [ ['title'    =>  'The Blue Elephant'                   ], ['title' => 'The Insult'                                       ], ['title' => 'The Sun of Gnosis'],                                                                                                             ], ],
               [  'tag' => ['Happy', 'Arabic', 'Kids'],         'movies'  =>  [ ['title'    =>  'The Knight and the Princess'         ], ['title' => 'Ramadan Mabrouk Abul-Alamein Hamouda'             ],                                                                                                                                               ], ],
               [  'tag' => ['Happy', 'Arabic', 'Friends'],      'movies'  =>  [ ['title'    =>  'Mosul'                               ], ['title' => 'The Blue Elephant'                                ], ['title' => 'The Insult'],                              ['title' => 'The Sun of Gnosis'],                 ['title' => 'The Blue Elephant 2'], ], ],
               [  'tag' => ['Happy', 'Korean', 'Alone'],        'movies'  =>  [ ['title'    =>  'Parasite'                            ], ['title' => 'Oldboy'                                           ], ['title' => 'The Yellow Sea'],                          ['title' => 'The Man from Nowhere'],                                                  ], ],
               [  'tag' => ['Happy', 'Korean', 'Date'],         'movies'  =>  [ ['title'    =>  'The Handmaiden'                      ], ['title' => 'New World'                                        ], ['title' => 'Sympathy for Mr. Vengeance'],                                                                                                    ], ],
               [  'tag' => ['Happy', 'Korean', 'Family'],       'movies'  =>  [ ['title'    =>  'Minari'                              ], ['title' => 'Parasite'                                         ], ['title' => 'Joint Security Area'],                     ['title' => 'A Taxi Driver'],                                                         ], ],
               [  'tag' => ['Happy', 'Korean', 'Kids'],         'movies'  =>  [  'title'    =>  'Swing Kids'                          ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Happy', 'Korean', 'Friends'],      'movies'  =>  [ ['title'    =>  'Oldboy'                              ], ['title' => 'Thirst'                                           ], ['title' => 'Sympathy for Mr. Vengeance'],                                                                                                    ], ],
               [  'tag' => ['Happy', 'Japanese', 'Alone'],      'movies'  =>  [ ['title'    =>  'Rurouni Kenshin Part I: Origins'     ], ['title' => 'Rurouni Kenshin: Final Chapter Part I - The Final'],                                                                                                                                               ], ],
               [  'tag' => ['Happy', 'Japanese', 'Date'],       'movies'  =>  [ ['title'    =>  'The Blind Swordsman: Zatoichi'       ], ['title' => 'Crows Zero'                                       ], ['title' => 'Crows Zero II'],                                                                                                                 ], ],
               [  'tag' => ['Happy', 'Japanese', 'Family'],     'movies'  =>  [  'title'    =>  'Confessions'                         ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Happy', 'Japanese', 'Kids'],       'movies'  =>  [ ['title'    =>  'Spirited Away'                       ], ['title' => 'From Up on Poppy Hill'                            ], ['title' => 'Detective Conan: The Darkest Nightmare'],                                                                                        ], ],
               [  'tag' => ['Happy', 'Japanese', 'Friends'],    'movies'  =>  [  'title'    =>  '13 Assassins'                        ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Happy', 'Indian', 'Alone'],        'movies'  =>  [ ['title'    =>  'Talaash'                             ], ['title' => 'Wanted'                                           ],                                                                                                                                               ], ],
               [  'tag' => ['Happy', 'Indian', 'Date'],         'movies'  =>  [ ['title'    =>  'Theri'                               ], ['title' => 'Ek Tha Tiger'                                     ],                                                                                                                                               ], ],
               [  'tag' => ['Happy', 'Indian', 'Family'],       'movies'  =>  [ ['title'    =>  'Taare Zameen Par'                    ], ['title' => 'Sultan'                                           ], ['title' => 'Don'],                                                                                                                           ], ],
               [  'tag' => ['Happy', 'Indian', 'Kids'],         'movies'  =>  [  'title'    =>  'Like Stars on Earth'                 ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Happy', 'Indian', 'Friends'],      'movies'  =>  [ ['title'    =>  'Visaaranai'                          ], ['title' => 'Fan'                                              ], ['title' => 'Agneepath'],                               ['title' => 'Wanted'],                                                                ], ],
               [  'tag' => ['Sad', 'English', 'Alone'],         'movies'  =>  [ ['title'    =>  'Charlie St. Cloud'                   ], ['title' => 'No Strings Attached'                              ],                                                                                                                                               ], ],
               [  'tag' => ['Sad', 'English', 'Date'],          'movies'  =>  [ ['title'    =>  'A Week Away'                         ], ['title' => 'Titanic'                                          ], ['title' => 'Remember Me'],                             ['title' => 'The Half of It'],                                                        ], ],
               [  'tag' => ['Sad', 'English', 'Family'],        'movies'  =>  [ ['title'    =>  'Dear John'                           ], ['title' => 'Bill & Ted Face the Music'                        ],                                                                                                                                               ], ],
               [  'tag' => ['Sad', 'English', 'Kids'],          'movies'  =>  [ ['title'    =>  'Soul'                                ], ['title' => 'Coco'                                             ],                                                                                                                                               ], ],
               [  'tag' => ['Sad', 'English', 'Friends'],       'movies'  =>  [ ['title'    =>  'The Butterfly Effect'                ], ['title' => 'Sound of Metal'                                   ], ['title' => 'Ocean\'s Eleven'],                         ['title' => 'The Hangover'],                                                          ], ],
               [  'tag' => ['Sad', 'Arabic', 'Alone'],          'movies'  =>  [  'title'    =>  '365 Days of Happiness'               ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Sad', 'Arabic', 'Date'],           'movies'  =>  [ ['title'    =>  'Omar'                                ], ['title' => 'Caramel'                                          ], ['title' => 'Harb Atalia'],                                                                                                                   ], ],
               [  'tag' => ['Sad', 'Arabic', 'Family'],         'movies'  =>  [  'title'    =>  '10 Days Before the Wedding'          ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Sad', 'Arabic', 'Kids'],           'movies'  =>  [  'title'    =>  'Theeb'                               ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Sad', 'Arabic', 'Friends'],        'movies'  =>  [ ['title'    =>  'Bosta'                               ], ['title' => 'The Game: Beast Level'                            ], ['title' => 'The Secret Men Club'],                                                                                                           ], ],
               [  'tag' => ['Sad', 'Korean', 'Alone'],          'movies'  =>  [ ['title'    =>  'Aelliseu'                            ], ['title' => 'The Swordsman'                                    ],                                                                                                                                               ], ],
               [  'tag' => ['Sad', 'Korean', 'Date'],           'movies'  =>  [ ['title'    =>  'Vincenzo'                            ], ['title' => 'True Beauty'                                      ], ['title' => 'Love Alarm'],                              ['title' => 'The Handmaiden'],                                                        ], ],
               [  'tag' => ['Sad', 'Korean', 'Family'],         'movies'  =>  [ ['title'    =>  'Descendants of the Sun'              ], ['title' => 'The Swordsman'                                    ],                                                                                                                                               ], ],
               [  'tag' => ['Sad', 'Korean', 'Kids'],           'movies'  =>  [ ['title'    =>  'A Brand New Life'                    ], ['title' => 'My Little Hero'                                   ],                                                                                                                                               ], ],
               [  'tag' => ['Sad', 'Korean', 'Friends'],        'movies'  =>  [  'title'    =>  'The Swordsman'                       ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Sad', 'Japanese', 'Alone'],        'movies'  =>  [  'title'    =>  'Close Range Love'                    ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Sad', 'Japanese', 'Date'],         'movies'  =>  [  'title'    =>  'Departures'                          ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Sad', 'Japanese', 'Family'],       'movies'  =>  [  'title'    =>  'Wood Job!'                           ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Sad', 'Japanese', 'Kids'],         'movies'  =>  [  'title'    =>  'Lu Over the Wall'                    ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Sad', 'Japanese', 'Friends'],      'movies'  =>  [  'title'    =>  'Boys Over Flowers: Final'            ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Sad', 'Indian', 'Alone'],          'movies'  =>  [  'title'    =>  'The Half of It'                      ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Sad', 'Indian', 'Date'],           'movies'  =>  [ ['title'    =>  'Aashiqui 2'                          ], ['title' => 'Love Aaj Kal'                                     ],                                                                                                                                               ], ],
               [  'tag' => ['Sad', 'Indian', 'Family'],         'movies'  =>  [ ['title'    =>  'Lootera'                             ], ['title' => 'Jannat 2'                                         ],                                                                                                                                               ], ],
               [  'tag' => ['Sad', 'Indian', 'Kids'],           'movies'  =>  [ ['title'    =>  'Kal Ho Naa Ho'                       ], ['title' => 'Kuch Kuch Hota Hai'                               ],                                                                                                                                               ], ],
               [  'tag' => ['Sad', 'Indian', 'Friends'],        'movies'  =>  [  'title'    =>  'Jab Tak Hai Jaan'                    ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Angry', 'English', 'Alone'],       'movies'  =>  [ ['title'    =>  'Spiral'                              ], ['title' => 'Stowaway'                                         ], ['title' => '6 Underground'],                                                                                                                 ], ],
               [  'tag' => ['Angry', 'English', 'Date'],        'movies'  =>  [  'title'    =>  'Things Heard & Seen'                 ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Angry', 'English', 'Family'],      'movies'  =>  [ ['title'    =>  'Monster Hunter'                      ], ['title' => 'The Bourne Supremacy'                             ],                                                                                                                                               ], ],
               [  'tag' => ['Angry', 'English', 'Kids'],        'movies'  =>  [ ['title'    =>  'Scoob!'                              ], ['title' => 'The Witches'                                      ],                                                                                                                                               ], ],
               [  'tag' => ['Angry', 'English', 'Friends'],     'movies'  =>  [ ['title'    =>  'Wrath of Man'                        ], ['title' => 'Spiral'                                           ], ['title' => 'Us'],                                                                                                                            ], ],
               [  'tag' => ['Angry', 'Arabic', 'Alone'],        'movies'  =>  [ ['title'    =>  'Transit Prisoner'                    ], ['title' => 'The Island'                                       ], ['title' => 'The Island 2'],                                                                                                                  ], ],
               [  'tag' => ['Angry', 'Arabic', 'Date'],         'movies'  =>  [ ['title'    =>  'Vernacular plan'                     ], ['title' => 'Soul Mate'                                        ],                                                                                                                                               ], ],
               [  'tag' => ['Angry', 'Arabic', 'Family'],       'movies'  =>  [ ['title'    =>  'The Goods'                           ], ['title' => 'The Island'                                       ], ['title' => 'The Island 2'],                                                                                                                  ], ],
               [  'tag' => ['Angry', 'Arabic', 'Kids'],         'movies'  =>  [  'title'    =>  'Shaw-Ming'                           ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Angry', 'Arabic', 'Friends'],      'movies'  =>  [ ['title'    =>  'The Replacement'                     ], ['title' => 'Al rahina'                                        ],                                                         ['title' => 'Escaping Tel Aviv'],                                                     ], ],
               [  'tag' => ['Angry', 'Korean', 'Alone'],        'movies'  =>  [ ['title'    =>  'The Swordsman'                       ], ['title' => 'New World'                                        ],                                                                                                                                               ], ],
               [  'tag' => ['Angry', 'Korean', 'Date'],         'movies'  =>  [ ['title'    =>  'Forgotten'                           ], ['title' => 'A Tale of Two Sisters'                            ],                                                                                                                                               ], ],
               [  'tag' => ['Angry', 'Korean', 'Family'],       'movies'  =>  [ ['title'    =>  'The Swordsman'                       ], ['title' => 'The Age of Shadows'                               ],                                                                                                                                               ], ],
               [  'tag' => ['Angry', 'Korean', 'Kids'],         'movies'  =>  [  'title'    =>  'Children...'                         ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Angry', 'Korean', 'Friends'],      'movies'  =>  [ ['title'    =>  'New World'                           ], ['title' => 'The Swordsman'                                    ], ['title' => 'The Villainess'],                                                                                                                ], ],
               [  'tag' => ['Angry', 'Japanese', 'Alone'],      'movies'  =>  [ ['title'    =>  'X Game'                              ], ['title' => 'Crows Explode'                                    ],                                                                                                                                               ], ],
               [  'tag' => ['Angry', 'Japanese', 'Date'],       'movies'  =>  [  'title'    =>  'Over Your Dead Body'                 ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Angry', 'Japanese', 'Family'],     'movies'  =>  [  'title'    =>  'Ju-on: The Grudge'                   ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Angry', 'Japanese', 'Kids'],       'movies'  =>  [  'title'    =>  'Another'                             ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Angry', 'Japanese', 'Friends'],    'movies'  =>  [ ['title'    =>  'Vampire Night'                       ], ['title' => 'The Suicide Manual'                               ],                                                                                                                                               ], ],
               [  'tag' => ['Angry', 'Indian', 'Alone'],        'movies'  =>  [  'title'    =>  'Mary Kom'                            ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Angry', 'Indian', 'Date'],         'movies'  =>  [ ['title'    =>  'Dhoom'                               ], ['title' => 'Kal Ho Naa Ho'                                    ],                                                                                                                                               ], ],
               [  'tag' => ['Angry', 'Indian', 'Family'],       'movies'  =>  [  'title'    =>  'Kabhi Khushi Kabhie Gham...'         ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Angry', 'Indian', 'Kids'],         'movies'  =>  [  'title'    =>  'My Name Is Khan'                     ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Angry', 'Indian', 'Friends'],      'movies'  =>  [  'title'    =>  'Kutte Ki Dum'                        ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'English', 'Alone'],      'movies'  =>  [ ['title'    =>  'Game Night'                          ], ['title' => 'Mean Girls'                                       ],                                                                                                                                               ], ],
               [  'tag' => ['Scared', 'English', 'Date'],       'movies'  =>  [  'title'    =>  'Due Date'                            ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'English', 'Family'],     'movies'  =>  [  'title'    =>  'Spy'                                 ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'English', 'Kids'],       'movies'  =>  [ ['title'    =>  'The War with Grandpa'                ], ['title' => 'The Croods: A New Age'                            ], ['title' => 'Tad: The Lost Explorer'],                                                                                                        ], ],
               [  'tag' => ['Scared', 'English', 'Friends'],    'movies'  =>  [ ['title'    =>  'The Hangover'                        ], ['title' => 'Ted'                                              ],                                                                                                                                               ], ],
               [  'tag' => ['Scared', 'Arabic', 'Alone'],       'movies'  =>  [  'title'    =>  'Hamlat Feraizar'                     ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Arabic', 'Date'],        'movies'  =>  [  'title'    =>  'Buying A Man'                        ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Arabic', 'Family'],      'movies'  =>  [  'title'    =>  'A Stand Worthy of Men'               ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Arabic', 'Kids'],        'movies'  =>  [  'title'    =>  'Mama\'s Boy'                         ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Arabic', 'Friends'],     'movies'  =>  [ ['title'    =>  'Monopoly (The Bank of Luck)'         ], ['title' => 'A Stand Worthy of Men'                            ],                                                                                                                                               ], ],
               [  'tag' => ['Scared', 'Korean', 'Alone'],       'movies'  =>  [  'title'    =>  'Windstruck'                          ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Korean', 'Date'],        'movies'  =>  [ ['title'    =>  'My Sassy Girl'                       ], ['title' => 'Spellbound'                                       ],                                                                                                                                               ], ],
               [  'tag' => ['Scared', 'Korean', 'Family'],      'movies'  =>  [  'title'    =>  'Lover\'s Concerto'                   ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Korean', 'Kids'],        'movies'  =>  [  'title'    =>  'Miracle in Cell No. 7'               ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Korean', 'Friends'],     'movies'  =>  [ ['title'    =>  'My Girl and I'                       ], ['title' => 'The Good the Bad the Weird'                       ],                                                                                                                                               ], ],
               [  'tag' => ['Scared', 'Japanese', 'Alone'],     'movies'  =>  [  'title'    =>  'Too Young to Die'                    ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Japanese', 'Date'],      'movies'  =>  [  'title'    =>  'The Apology King'                    ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Japanese', 'Family'],    'movies'  =>  [ ['title'    =>  'Fake mother'                         ], ['title' => 'Tampopo'                                          ],                                                                                                                                               ], ],
               [  'tag' => ['Scared', 'Japanese', 'Kids'],      'movies'  =>  [  'title'    =>  'No More Cry'                         ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Japanese', 'Friends'],   'movies'  =>  [  'title'    =>  'The Confidence Man JP: Princess'     ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Indian', 'Alone'],       'movies'  =>  [  'title'    =>  'Om Shanti Om'                        ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Indian', 'Date'],        'movies'  =>  [  'title'    =>  'Zero'                                ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Indian', 'Family'],      'movies'  =>  [  'title'    =>  '3 Idiots'                            ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Indian', 'Kids'],        'movies'  =>  [  'title'    =>  'Kuch Kuch Hota Hai'                  ],                                                                                                                                                                                                                    ],
               [  'tag' => ['Scared', 'Indian', 'Friends'],     'movies'  =>  [  'title'    =>  'Dilwale'                             ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'English', 'Alone'],    'movies'  =>  [  'title'    =>  'Shutter Island'                      ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'English', 'Date'],     'movies'  =>  [  'title'    =>  'Catch Me If You Can'                 ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'English', 'Family'],   'movies'  =>  [ ['title'    =>  'Sherlock Holmes'                     ], ['title' => 'Avengers: Endgame'                                ],                                                                                                                                               ], ],
               [  'tag' => ['chilling', 'English', 'Kids'],     'movies'  =>  [  'title'    =>  'The Boss Baby'                       ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'English', 'Friends'],  'movies'  =>  [ ['title'    =>  'Joker'                               ], ['title' => 'V for Vendetta'                                   ], ['title' => 'Suicide Squad'],                                                                                                                 ], ],
               [  'tag' => ['chilling', 'Arabic', 'Alone'],     'movies'  =>  [  'title'    =>  'The Man Who Sold His Skin'           ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Arabic', 'Date'],      'movies'  =>  [  'title'    =>  'For Sama'                            ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Arabic', 'Family'],    'movies'  =>  [  'title'    =>  'The Dissident'                       ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Arabic', 'Kids'],      'movies'  =>  [  'title'    =>  'Theeb'                               ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Arabic', 'Friends'],   'movies'  =>  [  'title'    =>  'Secrets of the Saqqara Tomb'         ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Korean', 'Alone'],     'movies'  =>  [  'title'    =>  'Memories of Murder'                  ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Korean', 'Date'],      'movies'  =>  [  'title'    =>  'A Moment to Remember'                ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Korean', 'Family'],    'movies'  =>  [ ['title'    =>  'Stinging Memories'                   ], ['title' => 'Train to Busan'                                   ],                                                                                                                                               ], ],
               [  'tag' => ['chilling', 'Korean', 'Kids'],      'movies'  =>  [  'title'    =>  'Hope'                                ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Korean', 'Friends'],   'movies'  =>  [  'title'    =>  'Always'                              ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Japanese', 'Alone'],   'movies'  =>  [  'title'    =>  'Mukoku'                              ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Japanese', 'Date'],    'movies'  =>  [  'title'    =>  'Another'                             ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Japanese', 'Family'],  'movies'  =>  [ ['title'    =>  'The Lion Standing in the Wind'       ], ['title' => 'Teketeke'                                         ], ['title' => 'I Was Born But...'],                                                                                                             ], ],
               [  'tag' => ['chilling', 'Japanese', 'Kids'],    'movies'  =>  [  'title'    =>  'Oppai Volleyball'                    ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Japanese', 'Friends'], 'movies'  =>  [  'title'    =>  'Tekken'                              ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Indian', 'Alone'],     'movies'  =>  [  'title'    =>  'Pink'                                ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Indian', 'Date'],      'movies'  =>  [  'title'    =>  'Bajrangi Bhaijaan'                   ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Indian', 'Family'],    'movies'  =>  [  'title'    =>  'Marakkar: Lion of the Arabian Sea'   ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Indian', 'Kids'],      'movies'  =>  [  'title'    =>  'PK'                                  ],                                                                                                                                                                                                                    ],
               [  'tag' => ['chilling', 'Indian', 'Friends'],   'movies'  =>  [  'title'    =>  'Vakeel Saab'                         ],                                                                                                                                                                                                                    ],
        ];

        /************************************
         *              INSERT THE DATA
         ***********************************/
        foreach($all_data as $row) {
            foreach ($row as $key => $data) {
                /** Create a Tag */
                if($key === 'tag') {
                    $this->tag = Tag::create([
                        'feeling'   => $data[0],
                        'language'  => $data[1],
                        'occasion'  => $data[2],
                    ]);
                }

                /** Create Movies && set up relation */
                if($key === 'movies') {
                    if(count($data) > 1) {
                        foreach($data as $movie)  {
                            $movie = Movie::create($movie);
                            $this->tag->movies()->attach($movie->id);
                        }
                    } else {
                        $movie = Movie::create($data);
                        $this->tag->movies()->attach($movie->id);
                    }
                }
            }
        }
    }

}

